import React, { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import TailwindIcon from "../../../icons/TailwindIcon"
import BurgerIcon from "../../../icons/BurgerIcon"
 
import {isEmpty} from 'lodash'

function Header({header}) {
    
    const {headerMenuItems, siteDescription, siteLogoUrl, siteTitle, favicon} = header || {};

    const [openMenu, setOpenMenu] = useState(false);
    
    return (
        <>
			<Head>
              <title>{siteTitle || 'NextJs Woocommerce'}</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href={favicon || "/favicon.ico"} />
           </Head>
			<div className="header">
				<nav className="bg-white py-5">
					<div className='flex items-center justify-between flex-wrap'>
                        <div className='flex items-center flex-shrink-0'>
                            <Link href="/">
                                <a>
                                    {
                                        siteLogoUrl ? (
                                            <img className='mr-2' src={siteLogoUrl} alt="siteLOGO" width={60} height={60}/>
                                        ) : (
                                            <TailwindIcon />
                                        )
                                    }
                                </a>
                            </Link>
                            <span>
                                <Link href="/">
                                    <a className='font-semibold text-2xl tracking-tight'>{siteTitle || 'WooBakery'}</a>
                                </Link>

                                {siteDescription ? (<p>
                                    {siteDescription}
                                </p>) : null}
                            </span>

                        </div>
                        <div className='block lg:hidden'>
                            <button onClick={() => setOpenMenu(!openMenu)} className='flex items-center px-3 py-2 border rounded text-black border-black'>
                                <BurgerIcon className="fill-current h-3 w-3"/>
                            </button>
                        </div>
                        <div className={`${openMenu ? 'max-h-full' : 'h-0'} w-full overflow-hidden lg:h-full flex-grow lg:items-center lg:flex px-12 lg:w-auto`}>
                            <div className='text-sm font-medium uppercase flex justify-between w-full'>
                                {!isEmpty(headerMenuItems) && headerMenuItems.length ? headerMenuItems.map(menuItem => (
                                    <Link href={menuItem?.url} key={menuItem?.ID}>
                                        <a className='block mt-4 lg:inline-block lg:mt-0 text-black' dangerouslySetInnerHTML={{ __html: menuItem?.title }} />
                                    </Link>
                                )) : null}
                            </div>
                        </div>
                    </div>
				</nav>
			</div>
		</>
    )
}

export default Header
