import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

import {isEmpty} from 'lodash'

function Header({header}) {
    
    const {headerMenuItems, siteDescription, siteLogoUrl, siteTitle, favicon} = header || {};
    
    return (
        <>
			<Head>
              <title>{siteTitle || 'NextJs Woocommerce'}</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href={favicon || "/favicon.ico"} />
           </Head>
			<div className="header">
				<nav className="bg-white py-5">
					<div className='flex items-center justify-between flex-wrap'>
                        <div className='flex items-center flex-shrink-0'>
                            <Link href="/">
                                <a>
                                    {
                                        siteLogoUrl ? (
                                            <img className='mr-2' src={siteLogoUrl} alt="siteLOGO" width={60} height={60}/>
                                        ) : (
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-radioactive" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFA029" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                                <path d="M13.5 14.6l3 5.19a9 9 0 0 0 4.5 -7.79h-6a3 3 0 0 1 -1.5 2.6" />
                                                <path d="M13.5 9.4l3 -5.19a9 9 0 0 0 -9 0l3 5.19a3 3 0 0 1 3 0" />
                                                <path d="M10.5 14.6l-3 5.19a9 9 0 0 1 -4.5 -7.79h6a3 3 0 0 0 1.5 2.6" />
                                            </svg>
                                        )
                                    }
                                </a>
                            </Link>
                            <span>
                                <Link href="/">
                                    <a className='font-semibold text-2xl tracking-tight'>{siteTitle || 'WooBakery'}</a>
                                </Link>

                                {siteDescription ? (<p>
                                    {siteDescription}
                                </p>) : null}
                            </span>

                        </div>
                        <div className='h-0 w-full overflow-hidden lg:h-full flex-grow lg:flex px-12'>
                            <div className='text-sm font-medium uppercase flex justify-between w-full'>
                                {!isEmpty(headerMenuItems) && headerMenuItems.length ? headerMenuItems.map(menuItem => (
                                    <Link href={menuItem?.url} key={menuItem?.ID}>
                                        <a className='block mt-4 lg:inline-block lg:mt-0 text-black' dangerouslySetInnerHTML={{ __html: menuItem?.title }} />
                                    </Link>
                                )) : null}
                            </div>
                        </div>
                    </div>
				</nav>
			</div>
		</>
    )
}

export default Header
